Lecture1
wi9916/Lectures pull request #1
Opened 2021-04-11 13:13 UTC by wi9916

Home work

2021-04-11 13:42 UTC, serhii-shkodenko requested changes
Виглядає досить добре. Будь-ласка, виправ ці зауваження. Ввечері, або можливо завтра ще гляну.

2021-04-11 13:42 UTC, serhii-shkodenko commented on HomeWork.cs
> +            String[] words = address.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).Skip(1).ToArray();
Відповідно до [конвенцій](визначення), у С# прийнято широко використовувати неявне визначення для типу локальної зміної у таких або схожих випадках. Використай `var` і тут. Продивись весь файл, будь ласка.

2021-04-11 13:42 UTC, serhii-shkodenko commented on HomeWork.cs
> +
Цей пустий рякдо можна видалити.

2021-04-11 13:42 UTC, serhii-shkodenko commented on HomeWork.cs
> +            decimal USD = 1.19M;
Також тут краще застосувати var. Назва змінної не зовсім оптимальна. Можливо, краще підійте іменник `coefficient`.

2021-04-11 13:42 UTC, serhii-shkodenko commented on HomeWork.cs
> +            if (destinations.Count() == clients.Count() && destinations.Count() == prices.Count() && destinations.Count() == currencies.Count())
А що буде, коли перевірку не будет пройдено? 

Щоб основний код не поміщати у блок if, краще написати щось на кшталт

```
if(!(ValidationIsComplete(...)))
{
    return fullPrice;
}

[основний код]
```

2021-04-11 13:42 UTC, serhii-shkodenko commented on HomeWork.cs
> +                    if (currency != "USD") listPrices[index] = CurrencyExchanger(listPrices[index], currency);
Блок `if` краще не писати в один рядок, це суттєво знижує читаність (readability).

2021-04-11 13:42 UTC, serhii-shkodenko commented on HomeWork.cs
> +                    //Console.WriteLine("{0} ==> {1}", listPrices[index],listPrices[index] - (listPrices[index] / 100) * discount[index]);
Закоментований код краще видаляти з ПР. Такого коду не має бути на продакшені.

2021-04-11 18:34 UTC, wi9916 commented
Виправив помилки

2021-04-12 19:49 UTC, wi9916 commented
нова версія

2021-04-13 18:47 UTC, serhii-shkodenko requested changes
Є суттєві недоліки. Виправ, будь-ласка.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +                streatAddress += word;
Одрук, `streat`. Має бути `street`.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +            return streatAddress;
Так само, одрук. Поправ, будь ласка.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +                "USD" => amount * coefficientUSD,
За умовами завдання, треба переводити євро у доллари, а не навпаки.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +                List<decimal> discount = new List<decimal>();
Використовуй нявне визначення типу змінної за допомогою `var`. Глянь у чаті, там було про це детальніше.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +                List<decimal> listPrices = new List<decimal>();
Так само.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +                    if (currency != "USD")
Тут у метод передається будь-яка валюта, окрім доллара, а в методі `CurrencyExchanger()` перевіряється якраз лише валюта USD. Виправ, будь ласка.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +                foreach (var destination in destinations)
Два рази перебираэться один і той же масив. Спробуй зменшити до одного разу.

2021-04-13 18:47 UTC, serhii-shkodenko commented on HomeWork.cs
> +                for (var index = 0; index < destinations.Count(); index++)
Тут ця ж колекція перебирається втретє. Це не дуже добре. Виправ, будь ласка.

2021-04-13 18:49 UTC, serhii-shkodenko commented on Lecture1.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lecture1", "Lecture1\Lecture1.csproj", "{2FE19EFF-454B-4BE3-93F6-9AE3FD494477}"
Тут помислка у розташуванні, через що не вантажиться проект. Проект був у директорії, потім його вручну перемістили, а посилання у солюшені залишилося те саме. Поправ, будь ласка.

2021-04-13 20:47 UTC, wi9916 commented
Виправив зауваження

2021-04-13 21:10 UTC, serhii-shkodenko requested changes
Ще невеликі зауваження.

2021-04-13 21:10 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +        private string CheckForNearStreat(string address)
Назва методу наштовхує на те, що тип повернення значення функції буде bool. З того що він робить, це щось типу `PrepareForChecking()`.

2021-04-13 21:10 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +            const decimal discountForInfant = 50;
Локальні константи не є найоптимальнішим вибором. Вони будуть органічно дивитись на рівні класу.

2021-04-13 21:10 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +                discount[infantId - 1] = discountForInfant;
У колекціях `infantIds` та `childrenIds` уже вказані індекси, починаючи з нуля.

2021-04-13 21:40 UTC, wi9916 commented
Виправив зауваження та дещо переорганызував код

2021-04-14 05:10 UTC, wi9916 commented
if (infantId <= discount.Count())
На
if (infantId < discount.Count())
Виправлю

2021-04-14 17:58 UTC, wi9916 commented
test Progect

2021-04-15 14:35 UTC, serhii-shkodenko requested changes

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +        const decimal discountForInfant = 50;
Відповідно до конвенцій, константи в С# мають імена у [PascalCase](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +        const decimal discountForChildren = 25;
Відповідно до конвенцій, константи в С# мають імена у [PascalCase](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +        const decimal discountForNearbyStreat = 15;
Відповідно до конвенцій, константи в С# мають імена у [PascalCase](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +        private decimal CurrencyExchanger(decimal amount, string currenciesFrom)
Назви методів у C# мають мати своєму складі дієслово.  Посилання на [конвенцію](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +            var discount = new List<decimal>();
Тут змінна має бути названа у множині.

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +            foreach (var childrenId in childrenIds)
Тут одрук. Краще назвати `childId`, а не `childrenId`.

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +                    discount[infantId] += discountForInfant;
Я не зрозумів, тут логіки, можешь пояснити?

2021-04-15 14:35 UTC, serhii-shkodenko commented on Lectures/HomeWork.cs
> +                    discount[childrenId] += discountForChildren;
Я не зрозумів, тут логіки, можешь пояснити?

2021-04-15 14:39 UTC, wi9916 commented on Lectures/HomeWork.cs
> +                    discount[childrenId] += discountForChildren;
Перевірка чи коректний ід замовлення з дитиною. Власне чи не виходить за межі ліста. І якщо невиходить призначається відповідна знижка на дитину

2021-04-15 14:39 UTC, wi9916 commented on Lectures/HomeWork.cs
> +                    discount[childrenId] += discountForChildren;
Тільки пропустив має бути сирого менше

2021-04-15 14:40 UTC, wi9916 commented on Lectures/HomeWork.cs
> +                    discount[childrenId] += discountForChildren;
*строго

2021-04-15 14:42 UTC, wi9916 commented on Lectures/HomeWork.cs
> +        const decimal discountForInfant = 50;
DiscountForInfant = 50?

2021-04-15 16:40 UTC, wi9916 commented
Виправив помилки з найменуванням констант та метода

2021-04-15 17:41 UTC, serhii-shkodenko approved these changes
Досить структуровано все виглядає, можна мержити.

2021-04-15 17:43 UTC, merged